apiVersion: v1
kind: ConfigMap
metadata:
  name: bet-configmap
data:
  BET_DB_HOST: "host.minikube.internal"
  BET_DB_USER: "authdbuser"
  BET_DB_NAME: "authdb"
  BET_DB_PORT: "5432"
  BET_HTTP_SERVER_HOST: "0.0.0.0"
  BET_HTTP_SERVER_PORT: "7000"
  BET_HTTP_SERVER_BACKLOG: "0"
  BET_THREAD_POOL_CORE_SIZE: "8"
  BET_THREAD_POOL_MAX_SIZE: "20"
  BET_THREAD_POOL_KEEP_ALIVE: "30"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"