apiVersion: v1
kind: Service
metadata:
  name: bet
spec:
  selector:
    app: bet
  type: ClusterIP
  ports:
    - name: bet
      port: 7000
      targetPort: 7000
      protocol: TCP
    - name: db
      port: 5432
      targetPort: 5432
      protocol: TCP
