apiVersion: v1
kind: ConfigMap
metadata:
  name: twemproxy-config
data:
  nutcracker.yaml: |
    redis_cluster:
      listen: 0.0.0.0:6379
      hash: fnv1a_64
      distribution: ketama
      auto_eject_hosts: true
      redis: true
      server_retry_timeout: 2000
      server_failure_limit: 1
      servers:
        - jwt-redis-slave-0:6379:1
        - jwt-redis-slave-1:6379:1
