apiVersion: batch/v1
kind: CronJob
metadata:
  name: schedule-game-start-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: schedule-game-start
              image: bryanwsebaraj/update
              args: ["scheduleGameStart"]
          restartPolicy: Never
