apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: auth
  type: ClusterIP
  ports:
    - name: auth
      port: 5000
      targetPort: 5000
      protocol: TCP
    - name: db
      port: 5432
      targetPort: 5432
      protocol: TCP
