apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-cleanup-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: pod-cleanup-servacc
    namespace: default
roleRef:
  kind: Role
  name: pod-cleanup-role
  apiGroup: rbac.authorization.k8s.io
