apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-game-end-settle-bet-cronjob
spec:
  schedule: "54 17 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: update-game-end-settle-bet
              image: bryanwsebaraj/update
              args: ["updateGameEndSettleBet"]
          restartPolicy: OnFailure