apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-groups-cronjob
spec:
  schedule: "56 17 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: update-groups
              image: bryanwsebaraj/update
              args: ["updateGroups"]
          restartPolicy: OnFailure