apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jwt-redis-slave
spec:
  serviceName: "jwt-redis-slave"
  replicas: 2
  selector:
    matchLabels:
      app: redis
      role: slave
  template:
    metadata:
      labels:
        app: redis
        role: slave
    spec:
      containers:
        - name: redis
          image: redis:6.2
          ports:
            - containerPort: 6379
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
          env:
            - name: REDIS_REPLICATION_MODE
              value: "slave"
            - name: REDIS_MASTER_SERVICE_HOST
              value: "jwt-redis-master"
            - name: REDIS_MASTER_SERVICE_PORT
              value: "6379"
            - name: REDIS_ALLOW_EMPTY_PASSWORD
              value: "yes"
          command:
            - redis-server
          args:
            - "--slaveof"
            - "$(REDIS_MASTER_SERVICE_HOST)"
            - "$(REDIS_MASTER_SERVICE_PORT)"
          volumeMounts:
            - name: redis-storage
              mountPath: /data
      volumes:
        - name: redis-storage
          emptyDir: {}
