apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rate-limiter
spec:
  serviceName: "rate-limiter"
  replicas: 6
  selector:
    matchLabels:
      app: rate-limiter
  template:
    metadata:
      labels:
        app: rate-limiter
    spec:
      containers:
        - name: redis
          image: redis:6.2
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: rate-limiter-data
              mountPath: /data
            - name: config-volume
              mountPath: /usr/local/etc/redis/redis.conf
              subPath: redis.conf
              readOnly: true
          command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
      volumes:
        - name: config-volume
          configMap:
            name: rate-limiter-config
  volumeClaimTemplates:
    - metadata:
        name: rate-limiter-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
