apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: "redis"
  replicas: 6
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:6.2
          ports:
            - containerPort: 6479
          volumeMounts:
            - name: redis-data
              mountPath: /data
            - name: config-volume
              mountPath: /usr/local/etc/redis/redis.conf
              subPath: redis.conf
              readOnly: true
          command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
      volumes:
        - name: config-volume
          configMap:
            name: redis-config
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
